module.exports = {
	baseUrl: "./",
	templates: [
		"FlightsSearchForm"
	],
	languages: [
		"en", "ru"
	],
	alias: {
		"FlightsSearchForm": "html/FlightsSearchForm"
	},
	paths: {
		"domReady":      "js/lib/requirejs/domReady",
		"text":          "js/lib/requirejs/text",
		"knockout":      "js/lib/knockout/v.3.2.0/knockout-3.2.0",
		"AppController": "js/NemoFrontEndController",
		"jquery":        "js/lib/jquery/v.2.1.3/jquery-2.1.3",
		"jqueryUI":      "js/lib/jqueryUI/v.1.11.4/jquery-ui",
		"jsCookie":      "js/lib/js.cookie/v.2.0.0/js.cookie",
		"tooltipster":   "js/lib/tooltipster/jquery.tooltipster.min",
		"numeralJS":     "js/lib/numeral.js/v.1.5.3/numeral.min",
		"mousewheel":    "js/lib/jquery.mousewheel/jquery.mousewheel.min",
		"touchpunch":    "js/lib/jquery.ui.touch-punch/v.0.2.3/jquery.ui.touch-punch.min",
		"i18n/common":            "build/i18n/[%-lang-%]/common",
		"i18n/pageTitles":        "build/i18n/[%-lang-%]/pageTitles",
		"i18n/dates":             "build/i18n/[%-lang-%]/dates",
		"i18n/FlightsSearchForm": "build/i18n/[%-lang-%]/FlightsSearchForm",
		},
	deps: [
		"i18n/common",
		"i18n/pageTitles",
		"i18n/dates",
		"i18n/FlightsSearchForm",
		"html/FlightsSearchForm",
		"js/vm/BaseDynamicModel",
		"js/vm/BaseStaticModel",
		"js/vm/BaseI18nizedModel",
		"js/vm/BaseControllerModel",
		"js/bindings/common",
		"js/vm/Flights/Common/Airline",
		"js/lib/jquery.pickmeup/jquery.pickmeup",
		"js/bindings/FlightsSearchForm",
		"js/vm/mobileDetect",
		"js/lib/jquery.chosen/v.1.4.2/chosen.jquery.min",
		"js/lib/mobile.detect.js/mobileDetect",
		"js/vm/Flights/SearchForm/Controller",
		"js/vm/Flights/SearchForm/Segment",
		"js/vm/Common/Date",
		"js/vm/Flights/Common/Geo",

		"domReady",
		"text",
		"knockout",
		"AppController",
		"jquery",
		"jqueryUI",
		"jsCookie",
		"numeralJS",
		"mousewheel",
		"touchpunch",
	],

	inlineText: true,
	optimize: "uglify2",
	name: "AppController",
	out: "./dist/nemo-search-[%-lang-%].js",
	preserveLicenseComments: false,
	generateSourceMaps: false,
	optimizeAllPluginResources: true
};